name: Deploy AWS-EC2

on:
   push:
    branches: [main]

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Fazendo configuracao do java
              uses: actions/setup-java@v3
              with:
                distribution: "zulu"
                java-version: "17"

            - name: Fazendo build do projeto
              run: mvn clean install && ls
   
            - name: Removendo jar antigo se existir
              uses: appleboy/ssh-action@v0.1.7
              with:
                host: ec2-15-228-41-74.sa-east-1.compute.amazonaws.com
                username: ec2-user
                key: ${{ secrets.EC2_SSH_KEY}}
                port: 22
                script: |
                    rm -rf /home/ec2-user/target 

            - name: Copiando JAR para EC2
              uses: appleboy/scp-action@master
              with:
                host: ec2-15-228-41-74.sa-east-1.compute.amazonaws.com
                username: ec2-user
                key: ${{ secrets.EC2_SSH_KEY }}
                port: 22
                source: "./target/jwt-verification-service.1.0.1.jar"
                target: "/home/ec2-user"

            - name: Parando instancia anteiror da API
              uses: appleboy/ssh-action@v0.1.7
              with:
                host: ec2-15-228-41-74.sa-east-1.compute.amazonaws.com
                username: ec2-user
                key: ${{ secrets.EC2_SSH_KEY }}
                port: 22
                script: |
                    PID=$(sudo lsof -ti :8080)
                    if [ ! -z "$PID" ]; then
                        sudo kill -9 $PID
                    fi

            - name: Executando nova instancia da API
              uses: appleboy/ssh-action@v0.1.7
              with:
                host: ec2-15-228-41-74.sa-east-1.compute.amazonaws.com
                username: ec2-user
                key: ${{ secrets.EC2_SSH_KEY }}
                port: 22
                script: |
                 nohup java -jar target/jwt-verification-service.1.0.1.jar > output.log 2>&1 &
